version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - name: ftpd_server
        image: stilliard/pure-ftpd
        environment:
          FTP_USER_NAME: circleci
          FTP_USER_PASS: pass
          FTP_USER_HOME: /home/circleci
    steps:
      - checkout
      - run: echo "hello"
